language: node_js
node_js:
  - "6.10"
  - "4.3"
env: NODE_ENV=production
deploy:
  on: # Only deploy a single version on master branch
    branch: master
    node: '4.3'
  provider: lambda
  function_name: process-sermons
  region: eu-west-1
  role: arn:aws:iam::727653659641:role/service-role/sermon-processing
  runtime: nodejs4.3
  handler_name: handler
  memory_size: 128 # MB
  timeout: 120 # seconds
  access_key_id:
    secure: hh+YbcauZ6Aq0Nr54W7D1OVHTijJhR8xdyxSTzRY1jA1TbjCk9zOlndKDRv5eVll/RL2Lso4ZpVkzxgPxJeZ4hoAqWLfzCfr4Ev28sMEg5N4ZMlqC/3G+u+xbhlQkpbyS2xR+CUYO8V1IryYCb8wlAMKiKUn7dhVzr9UIQj8JRzhe7eBbeGVl77DF20Vvrf6MJyAYpE7UVQzn1skE9S6l5PYEfGR3O8Z9G5boW0k84aDbglEEplLO/LtZYmsdby5FA8JLp0wObd0DG1Dy0/xuIBK7/l86ZfKcFJdObM7XG3ftIxrfKyekXOrYNEB6OlxmXDXUf9GdO+puP5jZgENlSWLs3WaWBeZTxXS0ARcIJXlSZ6cEkpNyAeOIi1e7wNGF6j9Qn+rH+Q0kvd6UWzfZMLZALzXFN1scXJZlBs4jwzzl7xCOrmFv4J9EaIewoajAA38NlVf/MK8c24/V4OV/rWpqOrw8aE7lCyre+7NbPcMG4P/oyeVoHq+Sy3H5tFt3NkhRZhZNS5ANqXwGqSj1rgLHvVL1XeyevwYulGwSv0zxshvbZ+jIC7bwFspUw6y4+b/LvaXUkEUPMS7gjnERjTPi1WLB10id6pSIdyhhkccVCT6nQ5EuwV/ajKOrMook8MHk5sqI807uyM5TP5MSQ1xqrBbgK0eKt30jSykYNQ=
  secret_access_key:
    secure: gnBlmxjuBVM24fwmIsWOD2d3ddtcrg6LtWt6uwevMUEl+GJj+OMEwe/RD0Mpxhp+t0CKcqpD1xVnIFw3cCHinu9STtp1b3+FP7+1CNRQN4fCpCNLGAhPLmJhsYjkNeR1iiMz6bWcAkiXVStvliVsao2TS0mnn7xtHpiy99AvEZ1jtuTzsyOR9xW/1MBLQMoiyezuvY5f5sWL0S/BcyCs6TG2E9MCzy+MWJuxgbMUy2W/ixHiIdHxJFIpNu0c+4Xn2fPZzckJSVWXaplZJNxtpu6UrLUJDLU79tzCVRSl8cmjs1kHwgufHrRAr4+AGolzIrOwbeRKtVKpm24JkuiT2S5uv7Zw2jhtbAzDguvvGlGurcCZWCwOzjcAZd9kv3vaya42h3J8SCHAId86BDa5MMPAdU6pmnMNpVSaOTcpLtTsJ81tF626/tkYsZ1iX6P5sBHLBOMApVKcMgfZVAJ4mgPiK8lXJiQ7e3hgE6L2vE6VeuVK7mPq/S057pAqGMEzbd4ti8bzEVtN0ZUZF+x5yuINUwRF1cRqQqI02VR10yQPKoCmg2CEuWHwzlgPtGCU45TMXM8sMGt2dLFt0X22TTF1zRCYm9XcgdWVnv/XOxDXZnn393nNA0r9ofGUPdd4fcDbPy1cnRNJJaDmi9N7fwHIKjN214ZabZAXnUYDCEg=
before_install: # Get the AWS CLI
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
after_deploy:
  - aws lambda update-function-configuration --function-name process-sermons --environment "Variables={SNS_TOPIC=$SNS_TOPIC}"
