language: node_js
node_js:
- '6.10'
cache: yarn
env:
  global:
  - secure: RQk9RriKvtSCEGrqbUB1KnDsx+DMlUfqLXwJeT+N91nkmBmLETNQnDMiyWsCbbIzMJ6gtnFQZ6GSoVh6xAXdMVtIguxCcwSeND8I9CJKiPvxHC/KgCDbWVDiHdVjNThIYWkFWSTwr6P8auEyioC+Wfe2etVGfEn7S41SY74SjzoUDP2kyJEoUR02Svj/qd/zgm7zpAQxHkjWV1B4bTCJ/J4x1Z3Xv5dr6IVsMDBNjnMWzhTKgA6wGF5WOZZ6h17Wrv5xN0Qjo/cYVx/TxQmFc8czg8BYn6D0V+/H+mXhBHJeFGqQJy/4OgIBr0JBJmOxoh/oUPT3bO2eaLSwRTmgp3M32hjGt8H7XkbFV8TZsL25Ms/k1ZdzPSopSmRnBkVm3tp7rocIG65WHSxJ7A6dl2A0PKFAxiiI01Q/ax2PMrpxpXStkwtWQt64RFZcjVYrcQwMv0zaNUBDwWOw/yHeL6n4eG9lam0ZzYcN/IcX672lXO0nBybUlJSH0vpIir7fjRrILo9sjTzgFiXlLG1+IL30yuYpB/LWgGFCwytwI/mC2q1CWi7C52T+aH+FAF4qg4vcdtAKADoghTjnR94mBSZXlQvrtovRjDy0brrnG/eNZR05e3G+/ihnn7CA32CUgWI7Upl9Y+IZZ82N4urgyovB35+mwLUfxXByPcJ0tDw=
deploy:
  on:
    branch: master
    node: '6.10'
  provider: lambda
  function_name: process-sermons
  region: eu-west-2
  role: arn:aws:iam::727653659641:role/service-role/sermon-processing
  runtime: nodejs6.10
  handler_name: handler
  memory_size: 1536
  timeout: 120
  access_key_id:
    secure: hh+YbcauZ6Aq0Nr54W7D1OVHTijJhR8xdyxSTzRY1jA1TbjCk9zOlndKDRv5eVll/RL2Lso4ZpVkzxgPxJeZ4hoAqWLfzCfr4Ev28sMEg5N4ZMlqC/3G+u+xbhlQkpbyS2xR+CUYO8V1IryYCb8wlAMKiKUn7dhVzr9UIQj8JRzhe7eBbeGVl77DF20Vvrf6MJyAYpE7UVQzn1skE9S6l5PYEfGR3O8Z9G5boW0k84aDbglEEplLO/LtZYmsdby5FA8JLp0wObd0DG1Dy0/xuIBK7/l86ZfKcFJdObM7XG3ftIxrfKyekXOrYNEB6OlxmXDXUf9GdO+puP5jZgENlSWLs3WaWBeZTxXS0ARcIJXlSZ6cEkpNyAeOIi1e7wNGF6j9Qn+rH+Q0kvd6UWzfZMLZALzXFN1scXJZlBs4jwzzl7xCOrmFv4J9EaIewoajAA38NlVf/MK8c24/V4OV/rWpqOrw8aE7lCyre+7NbPcMG4P/oyeVoHq+Sy3H5tFt3NkhRZhZNS5ANqXwGqSj1rgLHvVL1XeyevwYulGwSv0zxshvbZ+jIC7bwFspUw6y4+b/LvaXUkEUPMS7gjnERjTPi1WLB10id6pSIdyhhkccVCT6nQ5EuwV/ajKOrMook8MHk5sqI807uyM5TP5MSQ1xqrBbgK0eKt30jSykYNQ=
  secret_access_key:
    secure: gnBlmxjuBVM24fwmIsWOD2d3ddtcrg6LtWt6uwevMUEl+GJj+OMEwe/RD0Mpxhp+t0CKcqpD1xVnIFw3cCHinu9STtp1b3+FP7+1CNRQN4fCpCNLGAhPLmJhsYjkNeR1iiMz6bWcAkiXVStvliVsao2TS0mnn7xtHpiy99AvEZ1jtuTzsyOR9xW/1MBLQMoiyezuvY5f5sWL0S/BcyCs6TG2E9MCzy+MWJuxgbMUy2W/ixHiIdHxJFIpNu0c+4Xn2fPZzckJSVWXaplZJNxtpu6UrLUJDLU79tzCVRSl8cmjs1kHwgufHrRAr4+AGolzIrOwbeRKtVKpm24JkuiT2S5uv7Zw2jhtbAzDguvvGlGurcCZWCwOzjcAZd9kv3vaya42h3J8SCHAId86BDa5MMPAdU6pmnMNpVSaOTcpLtTsJ81tF626/tkYsZ1iX6P5sBHLBOMApVKcMgfZVAJ4mgPiK8lXJiQ7e3hgE6L2vE6VeuVK7mPq/S057pAqGMEzbd4ti8bzEVtN0ZUZF+x5yuINUwRF1cRqQqI02VR10yQPKoCmg2CEuWHwzlgPtGCU45TMXM8sMGt2dLFt0X22TTF1zRCYm9XcgdWVnv/XOxDXZnn393nNA0r9ofGUPdd4fcDbPy1cnRNJJaDmi9N7fwHIKjN214ZabZAXnUYDCEg=
before_deploy:
- npm prune --production
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
after_deploy:
- aws lambda update-function-configuration --function-name process-sermons --environment
  "Variables={NODE_ENV=production,SNS_TOPIC_ARN=$SNS_TOPIC_ARN}" > /dev/null
