language: node_js
node_js:
- '6.10'
cache: yarn
env:
  global:
    secure: qhLjazr2XpapweJFqsGj1PeSVD1Z+6DsCpv6aVYWLQ+KosV5fsRR8DiIfy9CzIwJ0/QPwUfBrNLvepVZgM1M212amghY1XWQ54YngiMe7odWuhXTUqdrSBUXYOqHoGA0Yg/X/PXPnY/o4UP1Lzz+kVHI6XyPOmFwTfIPmWS2oJggH6g9CW/0S8W8CQTJJ2Oq4lfZdm/DR4FdiScJMKKwQ9klWbTGo8KCyX1PaYSBxRJWgNQ1cWrlhfxFYO31sG919zn/blvblbejR3g33myx0FQ4L8JlarQ8Ht2rpMnP/g9oldb+V2GIz7AzWj6flLJfsv8Y5HCX0lmzZooYECYuV4AfGUuhy3pr4Dc+xjglYICJPUYAbOzRPGYnDB3R6yyUmxvU3afGqnXYvEJCKOsIhENCKiTu3w+Bl3zIbp1BF+kJ/8jJOUvoC7j5pLKYPqx65nkaCX4qW8oevrM2QzD+rB3TZaVHpHuPi7dVXzEcDTl1edQHZXc/EXm5JXBhNd1Eh0AZMGchXCoofllarRULmmgzQOdLjJK+1K6AIvP+xU88Cfjv66K06LrOoP+MhdJtRrfabKtSoUQi7x48on8oRVrFnqAYj2mYMvuuMaMnezoxjM84yBVlEEkuSIKUHDv/kd81RLyQaw+sqKXQPRVDiyuLnN3bHqxDUzKyFrSuSk4=

# TODO: Add GitHub releases deploy for tagged builds
deploy:
  on:
    branch: master
    node: '6.10'
  provider: lambda
  function_name: process-sermons
  region: eu-west-2
  role: arn:aws:iam::727653659641:role/service-role/sermon-processing
  runtime: nodejs6.10
  handler_name: handler
  memory_size: 1536
  timeout: 120
  access_key_id:
    secure: hh+YbcauZ6Aq0Nr54W7D1OVHTijJhR8xdyxSTzRY1jA1TbjCk9zOlndKDRv5eVll/RL2Lso4ZpVkzxgPxJeZ4hoAqWLfzCfr4Ev28sMEg5N4ZMlqC/3G+u+xbhlQkpbyS2xR+CUYO8V1IryYCb8wlAMKiKUn7dhVzr9UIQj8JRzhe7eBbeGVl77DF20Vvrf6MJyAYpE7UVQzn1skE9S6l5PYEfGR3O8Z9G5boW0k84aDbglEEplLO/LtZYmsdby5FA8JLp0wObd0DG1Dy0/xuIBK7/l86ZfKcFJdObM7XG3ftIxrfKyekXOrYNEB6OlxmXDXUf9GdO+puP5jZgENlSWLs3WaWBeZTxXS0ARcIJXlSZ6cEkpNyAeOIi1e7wNGF6j9Qn+rH+Q0kvd6UWzfZMLZALzXFN1scXJZlBs4jwzzl7xCOrmFv4J9EaIewoajAA38NlVf/MK8c24/V4OV/rWpqOrw8aE7lCyre+7NbPcMG4P/oyeVoHq+Sy3H5tFt3NkhRZhZNS5ANqXwGqSj1rgLHvVL1XeyevwYulGwSv0zxshvbZ+jIC7bwFspUw6y4+b/LvaXUkEUPMS7gjnERjTPi1WLB10id6pSIdyhhkccVCT6nQ5EuwV/ajKOrMook8MHk5sqI807uyM5TP5MSQ1xqrBbgK0eKt30jSykYNQ=
  secret_access_key:
    secure: gnBlmxjuBVM24fwmIsWOD2d3ddtcrg6LtWt6uwevMUEl+GJj+OMEwe/RD0Mpxhp+t0CKcqpD1xVnIFw3cCHinu9STtp1b3+FP7+1CNRQN4fCpCNLGAhPLmJhsYjkNeR1iiMz6bWcAkiXVStvliVsao2TS0mnn7xtHpiy99AvEZ1jtuTzsyOR9xW/1MBLQMoiyezuvY5f5sWL0S/BcyCs6TG2E9MCzy+MWJuxgbMUy2W/ixHiIdHxJFIpNu0c+4Xn2fPZzckJSVWXaplZJNxtpu6UrLUJDLU79tzCVRSl8cmjs1kHwgufHrRAr4+AGolzIrOwbeRKtVKpm24JkuiT2S5uv7Zw2jhtbAzDguvvGlGurcCZWCwOzjcAZd9kv3vaya42h3J8SCHAId86BDa5MMPAdU6pmnMNpVSaOTcpLtTsJ81tF626/tkYsZ1iX6P5sBHLBOMApVKcMgfZVAJ4mgPiK8lXJiQ7e3hgE6L2vE6VeuVK7mPq/S057pAqGMEzbd4ti8bzEVtN0ZUZF+x5yuINUwRF1cRqQqI02VR10yQPKoCmg2CEuWHwzlgPtGCU45TMXM8sMGt2dLFt0X22TTF1zRCYm9XcgdWVnv/XOxDXZnn393nNA0r9ofGUPdd4fcDbPy1cnRNJJaDmi9N7fwHIKjN214ZabZAXnUYDCEg=
before_deploy:
- npm prune --production
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
after_deploy:
  - aws lambda update-function-configuration --function-name process-sermons --environment "Variables={SNS_TOPIC_ARN=$SNS_TOPIC_ARN}" > /dev/null
